server:
  port: 8090

pod:
  id: 1

kafka:
  schema:
    registry:
      url: http://0.0.0.0:8081
  producer:
    batch: 100000
  topic:
    name: message-topic
    partition: 1
  bootstrap:
    address: localhost:9094
